server {
    listen 443 ssl;
    server_name {{ pillar['edge']['public_ip'] }};

    ssl_certificate     /etc/ssl/certs/edge.crt;
    ssl_certificate_key /etc/ssl/private/edge.key;

    location / {
        proxy_pass http://10.30.0.1:8080;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host  $host;
    }
}

server {
    listen 80;
    server_name {{ pillar['edge']['public_ip'] }};
    return 301 https://$host$request_uri;
}