flush ruleset
table inet filter {
  chain input {
    type filter hook input priority 0
    iif "lo" accept
    ct state established,related accept
    tcp dport 22 accept
    tcp dport 443 accept
    tcp dport 5432 accept
    udp dport 51820 accept
    iifname "wg0" accept

  }
}